#!/bin/bash
set -e
echo "start postrm \n"
if [ $1 = purge ] ; then 
    rm -f /etc/mini-isp.conf
fi

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi

#if pgrep -x ssh >/dev/null 2>&1
#then
#  echo "ssh is running will kill all of them"
#  pkill -x ssh >/dev/null 2>&1
#fi
exit 0
